# 可放入箱子的资源材质名称
resources:
  - IRON_INGOT
  - GOLD_INGOT
  - DIAMOND
  - EMERALD

# 消息配置
messages:
  success: "§a已放入 %material% x%amount%"
  full: "§c箱子空间不足，无法放入所有物品！"
  invalid_code: "§c[CQ]校验码无效！"
  
# 容器类型配置
container-types:
  - CHEST
  - ENDER_CHEST
  - TRAPPED_CHEST

hologram:
  text: "§7左键放入资源"
  duration: 0 # 悬浮文字持续时间(秒)，0表示永久
  scan-interval: 20 # 扫描间隔(tick)，20 tick = 1秒
  scan-radius: 10 # 扫描半径(格)

# 不要手动修改此校验码
verification-code: "无QWQ"